# -*- coding: utf-8 -*-
"""Generate the DESKTOP launcher for the A/H workbench, then install it.

Why a generator instead of writing the .bat directly:
  The launcher must reference a project path containing CJK characters, so
  the exact bytes - encoding, line endings, no BOM - matter. Generating them
  from one place keeps those decisions explicit and verifiable.

Encoding decision:
  The desktop launcher is UTF-8 (no BOM) + CRLF and switches the console to
  code page 65001 on its first line. The project's own launcher is ASCII-only
  for the opposite reason (see its header). Both conventions are in use on
  this machine already - the user's "video知识库剪贴板监控.bat" is UTF-8+chcp.
"""

import hashlib
import os
import shutil
import subprocess
import tempfile

PROJECT = 'D:\\' + '\u4e2a\u80a1\u5de5\u4f5c\u53f0'          # D:\个股工作台
PROJECT_BAT = '\u542f\u52a8\u5de5\u4f5c\u53f0.bat'            # 启动工作台.bat
DESKTOP = 'C:\\Users\\' + '\u5b9c\u6625\u6cd5\u9662' + '\\Desktop'

BODY = r'''@echo off
chcp 65001 >nul
setlocal EnableExtensions
title A/H Workbench - launcher

rem ======================================================================
rem  A/H Investment and Trading Workbench - DESKTOP launcher
rem
rem  This is a thin wrapper on purpose. All of the real logic - finding a
rem  real Python 3 interpreter, rejecting the Microsoft Store execution
rem  alias, and validating the project layout - lives in the workbench's
rem  own launcher:
rem
rem      {WB}\{BAT}
rem
rem  Keeping one copy of that logic means this icon cannot drift out of
rem  sync with the tested version.
rem
rem  ENCODING: this file is UTF-8 without BOM and switches the console to
rem  code page 65001 on the line above, because the path below contains CJK
rem  characters. The launcher inside the project is ASCII-only for exactly
rem  the opposite reason.
rem ======================================================================

set "WB={WB}"

rem  guard: if this wrapper is ever copied back into the project folder it
rem  would call itself forever - refuse instead of hanging.
if /i "%~f0"=="%WB%\{BAT}" (
  echo.
  echo   [ERROR] This is the desktop wrapper, but it is running from inside
  echo   [ERROR] the project folder. Use the project's own launcher instead:
  echo   [ERROR]   %WB%\{BAT}
  echo.
  pause
  exit /b 1
)

if not exist "%WB%\app\server.py" (
  echo.
  echo   [ERROR] Workbench not found at:
  echo   [ERROR]   %WB%
  echo.
  echo   [ERROR] If the project was moved or renamed, edit the "set WB="
  echo   [ERROR] line near the top of this file to the new location.
  echo.
  pause
  exit /b 1
)

echo   Project : %WB%
echo.

call "%WB%\{BAT}"
exit /b %ERRORLEVEL%
'''.replace('{WB}', PROJECT).replace('{BAT}', PROJECT_BAT)


def sha256(b):
    return hashlib.sha256(b).hexdigest()


def main():
    # CRLF everywhere, no bare LF: cmd is line-oriented and tolerates LF, but
    # labels/goto in the called script are safer with proper CRLF.
    text = BODY.replace('\r\n', '\n').replace('\n', '\r\n')
    data = text.encode('utf-8')

    assert not data.startswith(b'\xef\xbb\xbf'), 'must not emit a BOM'
    bare_lf = data.count(b'\n') - data.count(b'\r\n')

    # every line before the first CJK one must be ASCII, otherwise cmd would
    # mis-decode the pre-chcp part under the console's default code page.
    lines = data.split(b'\r\n')
    first_non_ascii = next(
        (i for i, ln in enumerate(lines) if any(c > 127 for c in ln)), None)

    print('=== generated launcher ===')
    print('  bytes        : %d' % len(data))
    print('  sha256       : %s' % sha256(data))
    print('  CRLF         : %d   bare LF: %d' % (data.count(b'\r\n'), bare_lf))
    print('  BOM          : %s' % ('present (BAD)' if data.startswith(b'\xef\xbb\xbf') else 'none'))
    print('  UTF-8 decode : %s' % ('ok' if data.decode('utf-8') else '?'))
    print('  first CJK line index: %s (all earlier lines ASCII: %s)'
          % (first_non_ascii,
             all(all(c < 128 for c in lines[j]) for j in range(first_non_ascii or 0))))
    print('  chcp on line : %s'
          % next((i + 1 for i, ln in enumerate(lines) if ln.strip().lower().startswith(b'chcp')),
                 'MISSING'))
    print()

    staged = os.path.join(tempfile.gettempdir(), '_desktop_launcher_stage.bat')
    with open(staged, 'wb') as f:
        f.write(data)

    target = os.path.join(DESKTOP, PROJECT_BAT)
    tmp_target = target + '.new'
    shutil.copyfile(staged, tmp_target)
    os.replace(tmp_target, target)          # atomic overwrite, no delete step

    got = open(target, 'rb').read()
    print('=== installed ===')
    print('  path   : %s' % target)
    print('  bytes  : %d' % len(got))
    print('  sha256 : %s' % sha256(got))
    print('  matches generated bytes: %s' % (got == data))

    # cross-check that the project the wrapper points at really is there
    print()
    print('=== target project ===')
    print('  %s\\app\\server.py  exists: %s'
          % (PROJECT, os.path.exists(os.path.join(PROJECT, 'app', 'server.py'))))
    print('  %s\\%s  exists: %s'
          % (PROJECT, PROJECT_BAT, os.path.exists(os.path.join(PROJECT, PROJECT_BAT))))


if __name__ == '__main__':
    main()
